blank_issues_enabled: false
contact_links:
  - name: Submit via Microsoft Form (no sign-in)
    url: https://forms.microsoft.com/r/epTjmNrDdE
    about: Use this link if you don’t have a GitHub account.
  - name: Read Positioning & Legal Notice
    url: https://trust-in-bharat.github.io/nirmata-site/legal/positioning/
    about: Framework scope, licensing, and disclaimers.
